name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - run: rustup component add rustfmt
    - run: rustup component add clippy

    - name: Setup fonts
      run: |
        mkdir -p .fonts

        # Download Fira Sans font
        wget -q "https://github.com/mozilla/Fira/archive/4.202.zip"
        unzip -q "4.202.zip"
        mv Fira-4.202/otf/*.otf .fonts/

        # Download Noto CJK font
        wget -q "https://github.com/notofonts/noto-cjk/raw/refs/tags/Sans2.004/Sans/OTC/NotoSansCJK-Regular.ttc" -O .fonts/NotoSansCJK-Regular.ttc

    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - run: cargo fetch --locked

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test
      env:
        # Write new snapshots into `.snap.new` files (for diffing via CI artifacts).
        INSTA_UPDATE: new
        # Set the path to the fonts directory for Typst.
        TYPST_FONT_PATH: ${{ github.workspace }}/.fonts

    - name: Upload snapshot artifacts on test failure
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-snapshots
        path: tests/snapshots/
        retention-days: 7
